#! /bin/env fish

# vim:ft=fish

set SCRIPTS_DIR $HOME/.config/bspwm/scripts
xsetroot -cursor_name left_ptr

# For sxhkd
set -gx SXHKD_SHELL /bin/bash
pgrep -x sxhkd >/dev/null || sxhkd &

# Multi-monitor support
set DOUBLE_MONITER (xrandr --listmonitors | grep DisplayPort)
if string length $DOUBLE_MONITER
    bspc monitor eDP -d 7 8 9 10
    bspc monitor DisplayPort-0 -d 1 2 3 4 5 6
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
end

# Borders and gaps
bspc config border_width 2
if string length $DOUBLE_MONITER
    bspc config window_gap 12
else
    bspc config window_gap 12
end

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config presel_feedback_color "#b7bdf8"
bspc config active_border_color "#b7bdf8"
# bspc config normal_border_color "#7d84a2"
bspc config focused_border_color "#c6a0f6"

# Special window rules
bspc config external_rules_command $HOME/.config/bspwm/scripts/external_rules.fish
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Wine state=floating border=off
bspc rule -a Gnome-screenshot state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a icalingua state=floating
bspc rule -a Fontweak state=floating
bspc rule -a Catfish state=floating
bspc rule -a Ario state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a blueman-manager state=floating
# bspc rule -a feh state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a zhumu state=floating
bspc rule -a "org.jackhuang.hmcl.Launcher" state=floating
bspc rule -a "Minecraft*" state=floating
bspc rule -a Steam state=floating
bspc rule -a "Clash for Windows" state=floating
bspc rule -a Motrix state=floating
bspc rule -a "*:*:Motrix WebExtension" state=floating
bspc rule -a "qq.exe" state=floating border=off
bspc rule -a "wechat.exe" state=floating border=off
bspc rule -a "tim.exe" state=floating border=off
bspc rule -a Xfce4-appfinder state=floating
bspc rule -a wechat-devtools state=floating
bspc rule -a guvcview state=floating
bspc rule -a wemeetapp state=floating border=off
bspc rule -a Todesk border=off
bspc rule -a Peek state=floating
bspc rule -a copyq state=floating
bspc rule -a bilibili state=floating
bspc rule -a lx-music-desktop state=floating border=off

# Autostart
fish $SCRIPTS_DIR/autostart.fish
