#! /bin/env fish

set SCRIPTS_DIR $HOME/.config/bspwm/scripts
xsetroot -cursor_name left_ptr

# For sxhkd
set -gx SXHKD_SHELL /bin/bash
pgrep -x sxhkd >/dev/null || sxhkd &

# Multi-monitor support
if xrandr --listmonitors | grep DisplayPort >/dev/null
    bspc monitor eDP -d 6 7 8
    bspc monitor DisplayPort-0 -d 1 2 3 4 5
else
    bspc monitor -d 1 2 3 4 5 6 7 8 # 9 10
end

# Borders and gaps
bspc config border_width 1
bspc config window_gap 16

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

# Special window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Wine state=floating
bspc rule -a "Gnome-screenshot" state=floating

# Autostart
fish $SCRIPTS_DIR/autostart.fish
